# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-15 15:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20, verbose_name='\u4ff1\u4e50\u90e8\u540d\u79f0')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u4ff1\u4e50\u90e8\u540d\u79f0',
                'verbose_name_plural': '\u4ff1\u4e50\u90e8\u540d\u79f0',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length='10', verbose_name='\u59d3\u540d')),
                ('gender', models.CharField(choices=[('male', '\u7537'), ('female', '\u5973')], default='female', max_length=6)),
                ('address', models.CharField(default='', max_length=100, verbose_name='\u5730\u5740')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True)),
                ('identity_card', models.TextField(max_length=18, verbose_name='\u8eab\u4efd\u8bc1')),
                ('weight', models.IntegerField(verbose_name='\u4f53\u91cd(\u5355\u4f4d\uff1a\u516c\u65a4)')),
                ('height', models.FloatField(verbose_name='\u8eab\u9ad8(\u5355\u4f4d\uff1a\u5398\u7c73)')),
                ('swim_clothes_size', models.CharField(choices=[('ml', 'ML'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XLL')], default='xl', max_length=5, verbose_name='\u6cf3\u8863\u5c3a\u7801')),
                ('t_short_size', models.CharField(choices=[('ml', 'ML'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XLL')], default='xl', max_length=5, verbose_name='\u6cf3\u8863\u5c3a\u7801')),
                ('shoe_size', models.CharField(choices=[('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43')], default='xl', max_length=2, verbose_name='\u62d6\u978b\u5c3a\u7801')),
                ('image', models.ImageField(default='image/default.png', upload_to='image/%Y/%m')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baoming.Club', verbose_name='\u4ff1\u4e50\u90e8\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u53c2\u8d5b\u961f\u5458',
                'verbose_name_plural': '\u53c2\u8d5b\u961f\u5458',
            },
        ),
    ]
