# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-15 15:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baoming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='leader',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4ff1\u4e50\u90e8\u7ba1\u7406\u5458'),
        ),
    ]
