# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-16 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baoming', '0002_club_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='address',
        ),
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=models.CharField(choices=[('male', '\u7537'), ('female', '\u5973')], default='male', max_length=6),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=10, verbose_name='\u59d3\u540d'),
        ),
    ]
