# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-16 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baoming', '0003_auto_20170416_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='identity_card',
            field=models.CharField(max_length=18, unique=True, verbose_name='\u8eab\u4efd\u8bc1'),
        ),
    ]
