# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-16 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baoming', '0004_auto_20170416_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=models.CharField(choices=[('male', '\u7537'), ('female', '\u5973')], default='male', max_length=6, verbose_name='\u6027\u522b'),
        ),
        migrations.AlterField(
            model_name='player',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='\u624b\u673a\u53f7\u7801'),
        ),
    ]
