# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-16 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baoming', '0005_auto_20170416_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=20, verbose_name='\u4ff1\u4e50\u90e8\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.FloatField(verbose_name='\u8eab\u9ad8(\u5355\u4f4d:\u5398\u7c73)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='mobile',
            field=models.CharField(default='', max_length=11, verbose_name='\u624b\u673a\u53f7\u7801'),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.IntegerField(verbose_name='\u4f53\u91cd(\u5355\u4f4d:\u516c\u65a4)'),
        ),
    ]
