# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-16 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baoming', '0006_auto_20170416_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.IntegerField(verbose_name='\u8eab\u9ad8(\u5355\u4f4d:\u5398\u7c73)'),
        ),
    ]
