# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-17 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baoming', '0007_auto_20170416_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(default='image/default.png', upload_to='image/%Y/%m', verbose_name='\u7528\u6237\u56fe\u50cf'),
        ),
    ]
