# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-19 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baoming', '0008_auto_20170417_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='t_short_size',
            field=models.CharField(choices=[('ml', 'ML'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XLL')], default='xl', max_length=5, verbose_name='T\u6064\u5c3a\u7801'),
        ),
    ]
