# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-30 18:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baoming', '0010_auto_20170429_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='\u4ff1\u4e50\u90e8\u7ba1\u7406\u5458'),
        ),
    ]
