# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-30 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baoming', '0011_auto_20170430_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='mobile',
            field=models.CharField(max_length=11, verbose_name='\u624b\u673a\u53f7\u7801'),
        ),
    ]
