# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-30 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baoming', '0012_auto_20170430_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubPlayer',
            fields=[
            ],
            options={
                'verbose_name': '\u4ff1\u4e50\u90e8\u53c2\u8d5b\u961f\u5458\u7ba1\u7406',
                'proxy': True,
                'verbose_name_plural': '\u4ff1\u4e50\u90e8\u53c2\u8d5b\u961f\u5458\u7ba1\u7406',
            },
            bases=('baoming.player',),
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': '\u5168\u90e8\u53c2\u8d5b\u961f\u5458', 'verbose_name_plural': '\u5168\u90e8\u53c2\u8d5b\u961f\u5458'},
        ),
    ]
