# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-17 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baoming', '0016_auto_20170502_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='swim_clothes_size',
            field=models.CharField(choices=[('ml', 'ML'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL')], default='xl', max_length=5, verbose_name='\u6cf3\u8863\u5c3a\u7801'),
        ),
        migrations.AlterField(
            model_name='player',
            name='t_short_size',
            field=models.CharField(choices=[('ml', 'ML'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL')], default='xl', max_length=5, verbose_name='T\u6064\u5c3a\u7801'),
        ),
    ]
