# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-28 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baoming', '0017_auto_20170517_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='shoe_size',
            field=models.CharField(choices=[('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43')], default='38', max_length=2, verbose_name='\u62d6\u978b\u5c3a\u7801'),
        ),
    ]
