# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-01 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baoming', '0018_auto_20170528_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.IntegerField(null=True, verbose_name='\u8eab\u9ad8(\u5355\u4f4d:\u5398\u7c73)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='mobile',
            field=models.CharField(max_length=11, null=True, verbose_name='\u624b\u673a\u53f7\u7801'),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.IntegerField(null=True, verbose_name='\u4f53\u91cd(\u5355\u4f4d:\u516c\u65a4)'),
        ),
    ]
